import type { FireCluster } from '@/types/fire';
import type { Resource } from '@/types/resource';
import type { EvacuationZone } from '@/types/evacuation';
import type { WeatherCondition } from '@/types/weather';

export function generateICS209(
  cluster: FireCluster,
  resources: Resource[],
  evacuationZones: EvacuationZone[],
  weather?: WeatherCondition | null
): string {
  const now = new Date();
  const deployed = resources.filter(
    (r) => r.assignedClusterId === cluster.id
  );
  const engines = deployed.filter((r) => r.type === 'engine').length;
  const helicopters = deployed.filter((r) => r.type === 'helicopter').length;
  const handCrews = deployed.filter((r) => r.type === 'hand_crew').length;
  const airTankers = deployed.filter((r) => r.type === 'air_tanker').length;
  const dozers = deployed.filter((r) => r.type === 'dozer').length;
  const waterTenders = deployed.filter((r) => r.type === 'water_tender').length;

  // Calculate containment from deployed resources
  const containmentPerType: Record<string, number> = {
    helicopter: 10, air_tanker: 12, engine: 6,
    hand_crew: 5, dozer: 8, water_tender: 4,
  };
  const containmentPct = Math.min(
    85,
    deployed
      .filter((r) => r.status === 'deployed' || r.status === 'en_route')
      .reduce((sum, r) => sum + (containmentPerType[r.type] || 3), 0)
  );

  const relatedZones = evacuationZones.filter(
    (z) => z.clusterId === cluster.id
  );
  const totalEvacPop = relatedZones.reduce((s, z) => s + z.population, 0);

  const hoursActive = Math.round(
    (now.getTime() - cluster.firstDetected.getTime()) / 3600000
  );

  const windDir = weather
    ? ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][
        Math.round((weather.windDirection || 0) / 45) % 8
      ]
    : '--';

  return `
═══════════════════════════════════════════════════════
               ICS-209  INCIDENT STATUS SUMMARY
═══════════════════════════════════════════════════════

1. INCIDENT NAME:          ${cluster.name}
2. INCIDENT NUMBER:        CA-${cluster.id.replace('cluster_', '').toUpperCase()}-${now.getFullYear()}
3. REPORT DATE/TIME:       ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
4. INCIDENT COMMANDER:     FireCommand AI (Palantir AIP)
5. INCIDENT TYPE:          Wildfire
6. STATE:                  California
7. COUNTY:                 --
8. LATITUDE:               ${cluster.centroid[1].toFixed(4)}°N
9. LONGITUDE:              ${cluster.centroid[0].toFixed(4)}°W

═══════════════════════════════════════════════════════
                    INCIDENT SUMMARY
═══════════════════════════════════════════════════════

10. INCIDENT SEVERITY:     ${cluster.severity.toUpperCase()}
11. FIRE RADIATIVE POWER:  ${cluster.totalFRP} MW
12. ESTIMATED SIZE:        ${cluster.estimatedAcres.toLocaleString()} acres
13. PERCENT CONTAINED:     ${containmentPct}%
14. DETECTION POINTS:      ${cluster.points.length}
15. HOURS ACTIVE:          ${hoursActive}
16. FIRST DETECTED:        ${cluster.firstDetected.toLocaleString()}
17. LAST DETECTED:         ${cluster.lastDetected.toLocaleString()}

═══════════════════════════════════════════════════════
                   WEATHER CONDITIONS
═══════════════════════════════════════════════════════

18. TEMPERATURE:           ${weather?.temperature ?? '--'}°F
19. RELATIVE HUMIDITY:     ${weather?.humidity ?? '--'}%
20. WIND SPEED:            ${weather?.windSpeed ?? '--'} mph
21. WIND DIRECTION:        ${windDir}
22. WIND GUSTS:            ${weather?.windGust ? Math.round(weather.windGust) : '--'} mph
23. FIRE WEATHER WARNING:  ${weather?.isFireWeatherWarning ? 'YES — RED FLAG' : 'No'}

═══════════════════════════════════════════════════════
                  RESOURCES ASSIGNED
═══════════════════════════════════════════════════════

24. TOTAL RESOURCES:       ${deployed.length}
    Engines:               ${engines}
    Helicopters:           ${helicopters}
    Hand Crews:            ${handCrews}
    Air Tankers:           ${airTankers}
    Dozers:                ${dozers}
    Water Tenders:         ${waterTenders}

${deployed.length > 0 ? deployed.map((r) => `    • ${r.name} (${r.type.replace('_', ' ')}) — ${r.status.replace('_', ' ')} from ${r.homeBase}`).join('\n') : '    No resources currently assigned.'}

═══════════════════════════════════════════════════════
                 EVACUATION STATUS
═══════════════════════════════════════════════════════

25. EVACUATION ZONES:      ${relatedZones.length}
26. POPULATION AT RISK:    ${totalEvacPop.toLocaleString()}

${relatedZones.length > 0 ? relatedZones.map((z) => `    • ${z.riskLevel.toUpperCase()} — Radius: ${z.radiusMiles} mi, Pop: ~${z.population.toLocaleString()}, Status: ${z.status}`).join('\n') : '    No evacuation zones active.'}

═══════════════════════════════════════════════════════
                      REMARKS
═══════════════════════════════════════════════════════

This report was generated by FireCommand, an AI-powered
wildfire incident command system using Palantir AIP Agent
and NASA FIRMS VIIRS NOAA-20 satellite fire detections.

Data sources: NASA FIRMS (satellite), NWS (weather),
CalFire (resources). AI analysis by Palantir AIP.

═══════════════════════════════════════════════════════
         END OF ICS-209 INCIDENT STATUS SUMMARY
═══════════════════════════════════════════════════════
`.trim();
}
