'use client';

import { X, Download, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface ICS209ModalProps {
  report: string;
  onClose: () => void;
}

export function ICS209Modal({ report, onClose }: ICS209ModalProps) {
  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ICS-209-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center" onClick={onClose}>
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

      {/* Modal */}
      <div
        className="relative w-[600px] max-h-[80vh] glass-panel rounded-lg border border-white/10 flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-white/10">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-orange-400" />
            <span className="text-sm font-semibold text-white tracking-wide">ICS-209 Incident Status Summary</span>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={handleDownload} className="h-7 text-xs text-muted-foreground hover:text-white gap-1">
              <Download className="h-3 w-3" />
              Download
            </Button>
            <Button variant="ghost" size="sm" onClick={onClose} className="h-7 w-7 p-0">
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4">
          <pre className="text-xs text-gray-300 font-mono leading-relaxed whitespace-pre-wrap">
            {report}
          </pre>
        </div>

        {/* Footer */}
        <div className="px-4 py-2 border-t border-white/10 flex justify-between items-center">
          <span className="text-[10px] text-muted-foreground/50 tracking-wider">GENERATED BY FIRECOMMAND / PALANTIR AIP</span>
          <span className="text-[10px] text-muted-foreground/50">{new Date().toLocaleString()}</span>
        </div>
      </div>
    </div>
  );
}
